# Generated by Django 6.0.2 on 2026-02-12 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paciente_alter_cita_options_alter_cita_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Total (S/)')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Abonado (S/)')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('yape_plin', 'Yape / Plin'), ('tarjeta', 'Tarjeta de Crédito/Débito')], max_length=20, verbose_name='Método de Pago')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Transacción')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas (Nro Operación/Detalles)')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='core.cita', verbose_name='Cita Asociada')),
            ],
            options={
                'verbose_name': 'Pago / Ingreso',
                'verbose_name_plural': 'Control de Caja (Pagos)',
            },
        ),
    ]
