# Generated by Django 6.0.2 on 2026-02-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Material')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Stock Actual')),
                ('stock_minimo', models.PositiveIntegerField(default=5, verbose_name='Alerta de Stock Mínimo')),
                ('unidad', models.CharField(choices=[('unidad', 'Unidades'), ('caja', 'Cajas'), ('litro', 'Litros'), ('botella', 'Botellas'), ('paquete', 'Paquetes')], default='unidad', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Caducidad')),
            ],
            options={
                'verbose_name': 'Insumo / Material',
                'verbose_name_plural': 'Inventario (Almacén)',
            },
        ),
    ]
