# Generated by Django 6.0.2 on 2026-02-12 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_insumo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('medicamentos', models.TextField(help_text='Ej: Amoxicilina 500mg - Tomar cada 8 horas por 5 días.', verbose_name='Medicamentos e Indicaciones')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('proxima_cita', models.DateField(blank=True, null=True, verbose_name='Sugerencia Próxima Cita')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cita', verbose_name='Cita Relacionada')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Receta Médica',
                'verbose_name_plural': 'Gestión de Recetas',
            },
        ),
    ]
