# Generated by Django 6.0.2 on 2026-02-13 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_receta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (S/)')),
                ('imagen', models.ImageField(upload_to='productos/', verbose_name='Foto del Producto')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
            ],
            options={
                'verbose_name': 'Producto en Venta',
                'verbose_name_plural': 'Tienda (Productos)',
            },
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_alergico', models.BooleanField(default=False, verbose_name='¿Tiene Alergias?')),
                ('alergias_detalle', models.CharField(blank=True, help_text='Ej: Penicilina, Látex', max_length=200, verbose_name='¿A qué es alérgico?')),
                ('tiene_enfermedad', models.BooleanField(default=False, verbose_name='¿Enfermedad Crónica?')),
                ('enfermedad_detalle', models.CharField(blank=True, help_text='Ej: Diabetes, Hipertensión', max_length=200, verbose_name='Nombre de la enfermedad')),
                ('toma_medicamentos', models.BooleanField(default=False, verbose_name='¿Toma Medicamentos?')),
                ('medicamentos_detalle', models.CharField(blank=True, help_text='Ej: Aspirina diaria', max_length=200, verbose_name='¿Cuáles?')),
                ('esta_embarazada', models.BooleanField(default=False, verbose_name='¿Está embarazada?')),
                ('observaciones', models.TextField(blank=True, verbose_name='Otras observaciones médicas')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Ficha Médica',
                'verbose_name_plural': 'Fichas Médicas',
            },
        ),
    ]
